"""Ingest OMEGA XV's bounded cutover-inventory research and payment tests."""
from __future__ import annotations
import os, uuid
from va_runtime.atomic_io import atomic_write_json, read_json_safe

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES_PATH = os.path.join(ROOT, 'data', 'sources.json')
CLOCKS_PATH = os.path.join(ROOT, 'data', 'cutover-inventory-clocks.json')
QUEUE_PATH = os.path.join(ROOT, 'data', 'idea-staging-queue.json')
RUNS_PATH = os.path.join(ROOT, 'data', 'research-runs.json')
RUN_ID = 'run-res-019-20260817-omega-xv-cutover-inventory-clock'
NOW = '2026-08-17T13:00:00+00:00'
NAMESPACE = uuid.UUID('c4a0ef35-7f26-45db-bbe6-ea0e9d9a4db0')

SOURCES = [
 ('s307','Import controls of food and feed - Questions and Answers','European Commission — DG SANTE','https://food.ec.europa.eu/horizontal-topics/official-controls-and-enforcement/import-controls-food-and-feed-qas_en',['Animal-origin imports require authorisation, traceability and official certificates','Non-compliant consignments may be refused, re-dispatched or destroyed']),
 ('s308','Get an export health certificate','GOV.UK / DEFRA / APHA','https://www.gov.uk/guidance/get-an-export-health-certificate',['GB animal-product exports to the EU require EHCs under current guidance','An official vet or inspector must review and certify the export']),
 ('s309','EU Steel Regulation: consultation on melt and pour evidence','European Commission — DG TRADE','https://policy.trade.ec.europa.eu/news/eu-steel-regulation-commission-launches-consultation-type-evidence-be-provided-country-melt-and-pour-2026-06-04_en',['The Commission consulted on evidence for country of melt and pour','The evidence object is distinct from simply displaying quota state']),
 ('s310','Veterinary sector: preparing your business','GOV.UK','https://www.gov.uk/government/publications/sps-agreement-preparing-your-business/veterinary-sector-preparing-your-business',['The future UK-EU SPS arrangement is a durability risk for a GB-only EHC wedge']),
 ('s311','BMPA update: EU antimicrobial export rules change from 3 September','British Meat Processors Association','https://britishmeatindustry.org/update/eu-antimicrobial-export-rules-change-from-3-september/',['Industry guidance reports a 3 September 2026 transition concern','This is industry implementation evidence, not legal certification authority']),
 ('s312','New certification requirements relating to antimicrobial medicinal products in POAO','British Frozen Food Federation','https://bfff.co.uk/new-certification-requirements-relating-to-use-of-antimicrobial-medicinal-products-in-poao/',['Industry guidance identifies stored products, third-country ingredients and supporting traceability evidence as practical issues']),
 ('s313','EU Steel Quota Tracker','Barrett Steel','https://www.barrettsteel.com/eu-steel-quota-tracker/',['A free tracker already exposes public quota state','A paid product must join quota state to a customer PO, clearance date and evidence']),
]

CUTOVERS = [
 {'id':'cutover-amr-poao-september-2026','name':'AMR export inventory-to-certificate transition','jurisdiction':'EU imports / GB export beachhead','at':'2026-09-03T00:00:00Z','objects':['finished SKU','batch or lot','ingredient','supplier','animal or product origin','planned shipment','EHC model'],'evidence':['supplier declaration','import record','production and processing record','storage record','batch traceability','ingredient specification','origin documentation','OV review'],'failures':['EHC delayed','consignment ineligible','border refusal','re-dispatch or destruction'],'half':'SHORT','drp':'HIGH','pcl':'HIGH','sources':['s307','s308','s311','s312']},
 {'id':'cutover-steel-melt-pour-october-2026','name':'Steel quota and melt-and-pour transaction transition','jurisdiction':'EU steel imports','at':'2026-10-01T00:00:00Z','objects':['purchase order','CN or quota line','origin','weight','customs value','ETA','clearance date','mill'],'evidence':['quota state','melt-and-pour evidence','supplier or mill documentation','customs scenario inputs'],'failures':['out-of-quota duty scenario','PO repricing','shipment delay','evidence escalation'],'half':'MEDIUM','drp':'MEDIUM','pcl':'MEDIUM','tcs':'50% out-of-quota cliff reported in brief; exact application must be refreshed','sources':['s309','s313']},
]

THESIS = [
 ('attestready-amr-export-inventory-certificate-preflight','AttestReady — AMR Export Inventory-to-Certificate Preflight',8.7,'VALIDATE_NOW','British meat, frozen-food, dairy/egg, aquaculture exporters, cold stores and specialist export advisers','Inventory-to-certifier evidence queue','3 paid audits from 30–50 qualified contacts; stronger signal is one real batch/source dataset followed by a repeat request','Short-half-life GB/EU wedge; future SPS simplification can reduce the addressable EHC workflow.'),
 ('steellandedrisk-steel-quota-tariff-cliff-preflight','SteelLandedRisk — Steel Quota/Tariff-Cliff Transaction Preflight',8.4,'VALIDATE_NOW','Steel importers, traders, procurement teams, customs advisers and manufacturers','PO-specific duty scenario plus melt-and-pour evidence readiness','5 paid PO audits or one real PO with a paid repeat/monitoring request','Free public quota trackers and customs brokers may absorb the control point; never guarantee quota allocation.'),
 ('microifud-synthetic-polymer-product-ifu-consistency-audit','MicroIFUD Gate — Synthetic-Polymer Product/IFU Consistency Audit',7.1,'NARROW_TEST','Synthetic-polymer medical-product manufacturers and regulatory teams','Product-to-IFU consistency preflight','One paid narrow product/IFU audit with a qualified reviewer','Consultancy-heavy and potentially covered by QMS/RA systems; no broad build.'),
]

def cid(slug): return f'candidate-{uuid.uuid5(NAMESPACE,slug)}'
def candidate(spec):
 slug,name,score,status,customer,control,gate,risk = spec; ident=cid(slug)
 return {'schemaVersion':'2.0.0','id':ident,'candidateId':ident,'candidateSlug':slug,'slug':f'{slug}-{ident}','name':name,'oneSentenceConcept':f'{control} for {customer}.','elevatorPitch':f'{control}; {risk}','detailedDescription':f'{control} for {customer}.','category':'Cutover Inventory Exposure','subcategory':'transaction preflight','tags':['omega-xv','cutover-inventory-clock','payment-validation','customer-evidence-unproven'],'status':'staged','evidenceStatus':'forcing_function_verified_payment_unproven','promotionEligible':False,'requiresExternalEvidence':True,'sourceReferences':[],'provenance':{'sourceType':'OMEGA XV Cutover Inventory Clock - source-backed research','researchRunId':RUN_ID,'notes':'The proposed price and verdict are hypotheses; no payment, buyer interview, or customer data is claimed.'},'atAGlance':{'targetCustomer':customer,'problemSolved':control,'whatToBuild':'Manual-first source-linked decision artifact; do not issue a certificate, guarantee quota, or replace the certifier/customs authority.','howItMakesMoney':'Paid audit/preflight is a pricing hypothesis.','whyCustomersPay':None,'estimatedEarningPotential':None,'startupCost':None,'overallScore':None,'confidenceScore':None,'mainAdvantage':'Joins authoritative external state to a customer transaction crossing a deadline.','mainRisk':risk,'bestNextValidationStep':gate},'researchAssessment':{'analystProvisionalOpportunityScore':score,'scoreScale':'0-10','scoreStatus':'provisional_not_ranking_eligible','capitalClockStatus':status,'controlPoint':control,'cutoverExposureMetric':'inventory_or_po_value × crossing_probability × evidence_deficiency × failure_severity','deadlineReliability': 'HIGH' if 'Attest' in name else 'MEDIUM','preCertifierLeverage':'HIGH' if 'Attest' in name else 'MEDIUM','noveltyDistance':'GENUINELY_NEW'},'validationChecklist':{'gateStatus':'approved_for_payment_validation_not_validated','passed':False,'passedCount':3,'failedCount':0,'unknownCount':5,'totalCriteria':8,'scorePercentage':37.5,'details':{'Forcing function verified':'pass','Named transaction control point':'pass','Negative evidence reviewed':'pass','Representative workflow confirmed':'unknown','Representative data obtained':'unknown','Paid willingness to pay':'unknown','Incumbent gap tested':'unknown','Repeat need tested':'unknown'}},'killCriteria':{'killFlagged':False,'killCount':0,'killConditions':{'No paid artifact at threshold':False,'Professional or official workflow already solves it':False,'Required upstream evidence inaccessible':False},'killFlags':[]},'createdAt':NOW,'updatedAt':NOW,'prioritizedForValidation':True,'reviewPriority':'urgent','priority':None}

def main():
 sources=read_json_safe(SOURCES_PATH,default_if_missing=[]); ids={x.get('id') for x in sources}
 for sid,title,pub,url,supports in SOURCES:
 if sid not in ids: sources.append({'id':sid,'title':title,'publisher':pub,'url':url,'supports':supports,'type':'official_or_primary_evidence','date':'2026','accessDate':'2026-08-17','confidenceLabel':'high' if sid in {'s307','s308','s309','s310'} else 'medium','sourceType':'primary' if sid not in {'s311','s312','s313'} else 'industry_or_market','researchRound':'omega-xv-cutover-inventory-2026-08-17','ideaIds':[],'visibility':'PUBLIC','sourceClass':'PRIMARY_OR_OFFICIAL' if sid in {'s307','s308','s309','s310'} else 'COMPANY_OR_INDUSTRY','evidenceEligible':True,'provenanceEligible':True})
 clocks=[]
 for c in CUTOVERS: clocks.append({'cutoverId':c['id'],'name':c['name'],'jurisdiction':c['jurisdiction'],'cutoverAt':c['at'],'affectedObjects':c['objects'],'requiredEvidence':c['evidence'],'failureModes':c['failures'],'halfLife':c['half'],'deadlineReliability':c['drp'],'tariffCliffSeverity':c.get('tcs'),'preCertifierLeverage':c['pcl'],'sourceRefs':c['sources'],'status':'UPCOMING'})
 queue=read_json_safe(QUEUE_PATH,default_if_missing=[]); by={x.get('candidateSlug'):i for i,x in enumerate(queue)}
 for spec in THESIS:
  x=candidate(spec)
  if spec[0] in by: queue[by[spec[0]]] = x
  else: queue.append(x); by[spec[0]]=len(queue)-1
 run={'runId':RUN_ID,'baselineCommit':'c665bd900f3f6e68dd1fefaf1599713076266854','questions':['What already-produced inventory or open PO crosses a future state boundary?','What evidence does the certifier, customs authority or buyer need next?','Is the clock urgent enough to pay before the wedge expires?'],'queries':['EU AMR animal-origin import certification September 2026','GB EHC official vet stored inventory traceability','EU steel quota melt and pour evidence October 2026','free steel quota tracker substitute','UK-EU SPS agreement durability risk'],'sourceCandidates':[x[0] for x in SOURCES],'inclusions':[cid(x[0]) for x in THESIS],'exclusions':['generic EHC SaaS','generic veterinarian AI','generic steel quota tracker','generic regulatory deadline tracker','OrganicCOI as a new thesis after waiver risk'],'claimsChanged':['Cutover Inventory Exposure is now represented as a separate schema and two source-linked clocks.','AttestReady and SteelLandedRisk are staged for payment validation only; MicroIFUD remains a narrow test.','The repository records the certifier/customs boundary and explicit negative evidence rather than claiming certification or quota allocation.'],'validationPriorityQueue':[{'rank':i+1,'proposal':x[1],'status':x[3]} for i,x in enumerate(THESIS)],'immediateExperiments':[{'proposal':x[1],'offer':'manual-first paid decision artifact','acceptance':x[6]} for x in THESIS],'methodVersion':'omega-xv-cutover-inventory-clock-v1','agent':'research-intelligence-agent','startedAt':NOW,'endedAt':NOW,'reviewStatus':'approved_for_payment_validation_not_canonical_promotion'}
 runs=read_json_safe(RUNS_PATH,default_if_missing=[]); idx=next((i for i,x in enumerate(runs) if x.get('runId')==RUN_ID),None)
 if idx is None:runs.append(run)
 else:runs[idx]=run
 atomic_write_json(SOURCES_PATH,sources); atomic_write_json(CLOCKS_PATH,{'schemaVersion':'1.0.0','generatedAt':NOW,'records':clocks}); atomic_write_json(QUEUE_PATH,queue); atomic_write_json(RUNS_PATH,runs)
 print('[OK] Recorded 2 cutover clocks, 3 payment-validation hypotheses, and negative evidence boundaries.')
if __name__=='__main__': main()
